# Generated by Django 5.1.3 on 2024-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('educationLevel', models.CharField(max_length=255)),
                ('jobTitle', models.TextField(blank=True)),
                ('yearsOfExperience', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
